### PR TITLE
Playlist features

### PR DESCRIPTION
**Pull request by istnv**
Added option to increase timer resolution.
Defaults to false with 500ms timer.

### CODE REVIEW

**Comment by krocheck** [comment]
@istnv can you explain the logic you changed @ line 480?  I'm may not be following it correctly, so I want to make sure its doing what you're expecting it to.

**Comment by istnv** [comment]
Reading through after some sleep. 
It should be `(!(IS_STOPPED) && (self.hires))`
I'll have another patch in a while.
I also found another way to get the player out of sync with the modules internal playlist so I'm working on that.

**Comment by krocheck** [comment]
Sounds good ... just drop all that here.

**Comment by istnv** [comment]
Should be ready, now.
Playlist optimization was too aggressive and missed changes if the playlist was re-sorted.

**Pull request merged**
